'use client';
import { DndContext, PointerSensor, closestCorners, useSensor, useSensors, type DragEndEvent } from '@dnd-kit/core';
import { SortableContext, verticalListSortingStrategy } from '@dnd-kit/sortable';
import type { CrmSettings, Deal, DealFile, DealStatus, DocumentKind, DocumentTemplateConfig } from '@/types/crm';
import { DealCard, KanbanColumn } from './DealCard';
export function DealBoard({ columns, statuses, statusTitles, statusStyles, settings, dealFiles, activeDocumentTemplates, hasSearchQuery, onDragEnd, onCreateDeal, onEditDeal, onDeleteDeal, onOpenReminder, onCreateDrawing, onGenerateDocument, onDealFilesSelected }: { columns: Record<DealStatus, Deal[]>; statuses: DealStatus[]; statusTitles: Record<DealStatus, string>; statusStyles: Record<DealStatus, string>; settings: CrmSettings; dealFiles: DealFile[]; activeDocumentTemplates: DocumentTemplateConfig[]; hasSearchQuery: boolean; onDragEnd: (event: DragEndEvent) => void; onCreateDeal: () => void; onEditDeal: (deal: Deal) => void; onDeleteDeal: (deal: Deal) => void; onOpenReminder: (clientId: string, dealId: string) => void; onCreateDrawing: (dealId: string) => void; onGenerateDocument: (deal: Deal, kind: DocumentKind) => void; onDealFilesSelected: (dealId: string, files: File[]) => void }) {
  const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 8 } }));
  return <section className="flex-1 px-5 py-6 sm:px-8"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-2xl font-bold text-slate-950">Сделки</h2><p className="text-sm text-slate-500">Канбан-доска проектных заказов.</p></div><button type="button" onClick={onCreateDeal} className="rounded-xl bg-slate-950 px-4 py-2 text-sm font-bold text-white">Новая сделка</button></div><DndContext sensors={sensors} collisionDetection={closestCorners} onDragEnd={onDragEnd}><div className="grid gap-4 xl:grid-cols-4">{statuses.map((status) => <section key={status} className="min-w-0"><div className={`mb-3 rounded-2xl border p-3 ${statusStyles[status] ?? 'border-slate-200 bg-white'}`}><h3 className="font-bold text-slate-950">{statusTitles[status] ?? status}</h3><p className="text-sm text-slate-500">{columns[status]?.length ?? 0} сделок</p></div><SortableContext items={(columns[status] ?? []).map((deal) => deal.id)} strategy={verticalListSortingStrategy}><KanbanColumn status={status}>{(columns[status] ?? []).map((deal, index) => <DealCard key={deal.id} deal={deal} index={index} status={status} isDragDisabled={hasSearchQuery} statusTitles={statusTitles} settings={settings} dealFiles={dealFiles} activeDocumentTemplates={activeDocumentTemplates} onEditDeal={onEditDeal} onDeleteDeal={onDeleteDeal} onOpenReminder={onOpenReminder} onCreateDrawing={onCreateDrawing} onGenerateDocument={onGenerateDocument} onDealFilesSelected={onDealFilesSelected} />)}</KanbanColumn></SortableContext></section>)}</div></DndContext></section>;
}
