'use client';
import { Save, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import type { Client, Deal, DealCostCategory, DealCostItem, DealFinancials, DealStatus } from '@/types/crm';
import { createEmptyDealFinancials } from '@/lib/dealFinancials';
export type DealFormMode = 'create' | 'edit' | null;
export type DealFormValues = Pick<Deal, 'title' | 'clientId' | 'status' | 'owner' | 'dueDate' | 'revenueAmount' | 'currency' | 'financials' | 'notes'>;
export const EMPTY_DEAL_FORM: DealFormValues = { title: '', clientId: '', status: 'lead', owner: '', dueDate: '', revenueAmount: 0, currency: 'RUB', financials: createEmptyDealFinancials(), notes: '' };
export function normalizeDealFinancials(financials?: Partial<DealFinancials>, categories: { id: DealCostCategory }[] = [{ id: 'rawMaterial' }, { id: 'factoryLoading' }, { id: 'workshopDelivery' }, { id: 'employeeLabor' }, { id: 'paintShopLogistics' }, { id: 'painting' }, { id: 'other' }]): DealFinancials { return categories.map((category) => category.id).reduce((result, category) => ({ ...result, [category]: financials?.[category] ?? [] }), {} as DealFinancials); }
export function createDealFormValues(deal?: Deal | null, fallbackClientId = ''): DealFormValues { if (!deal) return { ...EMPTY_DEAL_FORM, clientId: fallbackClientId }; return { title: deal.title, clientId: deal.clientId, status: deal.status, owner: deal.owner, dueDate: deal.dueDate, revenueAmount: deal.revenueAmount, currency: deal.currency, financials: normalizeDealFinancials(deal.financials), notes: deal.notes }; }
export function normalizeDealFormValues(values: DealFormValues): DealFormValues { return { title: values.title.trim(), clientId: values.clientId.trim(), status: values.status, owner: values.owner.trim(), dueDate: values.dueDate.trim(), revenueAmount: Number(values.revenueAmount) || 0, currency: 'RUB', financials: normalizeDealFinancials(values.financials), notes: values.notes.trim() }; }
export function validateDealForm(values: DealFormValues, clients: Client[], enabledStatuses: DealStatus[]): string | null { const normalized = normalizeDealFormValues(values); if (!normalized.title) return 'Укажите название сделки.'; if (!normalized.clientId || !clients.some((client) => client.id === normalized.clientId)) return 'Выберите клиента из базы.'; if (!enabledStatuses.includes(normalized.status)) return 'Выберите корректный статус сделки.'; if (!normalized.owner) return 'Укажите ответственного менеджера.'; if (!/^\d{4}-\d{2}-\d{2}$/.test(normalized.dueDate)) return 'Укажите плановый срок в формате даты.'; if (normalized.revenueAmount <= 0) return 'Укажите положительную выручку сделки.'; return null; }
export function createDealCostItem(category: DealCostCategory): DealCostItem { return { id: `cost-${category}-${Date.now()}-${Math.random().toString(16).slice(2)}`, category, title: '', amount: 0, hours: category === 'employeeLabor' ? 0 : undefined, hourlyRate: category === 'employeeLabor' ? 0 : undefined, comment: '' }; }
export function DealForm({ mode, values, error, clients, statuses, statusTitles, onChangeField, onSubmit, onClose }: { mode: DealFormMode; values: DealFormValues; error: string | null; clients: Client[]; statuses: DealStatus[]; statusTitles: Record<DealStatus, string>; onChangeField: (field: keyof DealFormValues, value: string) => void; onSubmit: (event: React.FormEvent<HTMLFormElement>) => void; onClose: () => void }) {
  if (!mode) return null;
  return <section className="border-b border-slate-200 bg-white px-5 py-5 sm:px-8"><form onSubmit={onSubmit} className="rounded-3xl border border-slate-200 bg-slate-50 p-4"><div className="mb-4 flex items-start justify-between gap-3"><div><h2 className="text-xl font-bold text-slate-950">{mode === 'create' ? 'Новая сделка' : 'Редактирование сделки'}</h2><p className="text-sm text-slate-500">Заполните параметры сделки и сохраните изменения.</p></div><Button type="button" variant="ghost" onClick={onClose}><X className="h-4 w-4" /></Button></div><div className="grid gap-3 md:grid-cols-2"><Input value={values.title} onChange={(event) => onChangeField('title', event.target.value)} placeholder="Название сделки *" /><select value={values.clientId} onChange={(event) => onChangeField('clientId', event.target.value)} className="rounded-md border border-slate-200 bg-white px-3 py-2 text-sm outline-none transition focus:border-slate-400">{clients.map((client) => <option key={client.id} value={client.id}>{client.name} · {client.company}</option>)}</select><select value={values.status} onChange={(event) => onChangeField('status', event.target.value)} className="rounded-md border border-slate-200 bg-white px-3 py-2 text-sm outline-none transition focus:border-slate-400">{statuses.map((status) => <option key={status} value={status}>{statusTitles[status] ?? status}</option>)}</select><Input value={values.owner} onChange={(event) => onChangeField('owner', event.target.value)} placeholder="Ответственный *" /><Input type="date" value={values.dueDate} onChange={(event) => onChangeField('dueDate', event.target.value)} /><Input type="number" value={values.revenueAmount} onChange={(event) => onChangeField('revenueAmount', event.target.value)} placeholder="Выручка *" /><textarea value={values.notes} onChange={(event) => onChangeField('notes', event.target.value)} placeholder="Заметки" className="min-h-24 rounded-md border border-slate-200 bg-white px-3 py-2 text-sm outline-none transition focus:border-slate-400 md:col-span-2" /></div>{error ? <p className="mt-3 text-sm font-semibold text-red-700">{error}</p> : null}<div className="mt-4 flex flex-wrap gap-2"><Button type="submit"><Save className="h-4 w-4" />Сохранить</Button><Button type="button" variant="outline" onClick={onClose}>Отмена</Button></div></form></section>;
}
