'use client';
import { CheckCircle2 } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import type { Client, Deal, Reminder } from '@/types/crm';
import { formatDateTime } from '@/lib/documents/generateDocumentText';
import { isReminderOverdue, REMINDER_PRIORITY_TITLES, REMINDER_TYPE_TITLES, type ReminderFilter } from '@/hooks/useReminders';
export function RemindersPanel({ reminders, clients, deals, reminderFilter, setReminderFilter, onCompleteReminder }: { reminders: Reminder[]; clients: Client[]; deals: Deal[]; reminderFilter: ReminderFilter; setReminderFilter: (filter: ReminderFilter) => void; onCompleteReminder: (id: string) => void }) {
  return <section className="border-b border-slate-200 bg-white px-5 py-4 sm:px-8"><div className="mb-3 flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-lg font-bold text-slate-950">Напоминания</h2><p className="text-sm text-slate-500">Фильтры: сегодня, просрочено и будущие задачи по клиентам и сделкам.</p></div><div className="flex flex-wrap gap-2">{(['today', 'overdue', 'future'] as ReminderFilter[]).map((filter) => <Button key={filter} type="button" variant={reminderFilter === filter ? 'default' : 'outline'} size="sm" onClick={() => setReminderFilter(filter)}>{filter === 'today' ? 'Сегодня' : filter === 'overdue' ? 'Просрочено' : 'Будущие'}</Button>)}</div></div>{reminders.length > 0 ? <div className="grid gap-3 lg:grid-cols-3">{reminders.map((reminder) => { const reminderDeal = deals.find((deal) => deal.id === reminder.dealId); const reminderClient = clients.find((client) => client.id === reminder.clientId); return <article key={reminder.id} className={`rounded-2xl border p-3 text-sm ${isReminderOverdue(reminder) ? 'border-red-200 bg-red-50' : 'border-slate-200 bg-slate-50'}`}><div className="flex items-start justify-between gap-3"><div><p className="font-bold text-slate-950">{reminder.title}</p><p className="mt-1 text-slate-600">{formatDateTime(reminder.dueAt)} · {REMINDER_TYPE_TITLES[reminder.type]}</p></div><Badge variant="outline">{REMINDER_PRIORITY_TITLES[reminder.priority]}</Badge></div>{reminder.description ? <p className="mt-2 leading-5 text-slate-600">{reminder.description}</p> : null}<p className="mt-2 text-xs text-slate-500">{reminderClient?.name ?? 'Клиент не найден'} · {reminderDeal?.title ?? 'Сделка не найдена'} · {reminder.managerId}</p>{!reminder.isDone ? <Button type="button" size="sm" className="mt-3" onClick={() => onCompleteReminder(reminder.id)}><CheckCircle2 className="h-4 w-4" /> Выполнено</Button> : <p className="mt-3 text-xs font-semibold text-emerald-700">Выполнено</p>}</article>; })}</div> : <p className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-4 text-sm text-slate-500">Нет напоминаний по выбранному фильтру.</p>}</section>;
}
