'use client';
import { Mail, MapPin, MessageCircle, Pencil, Phone, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import type { Client, Deal } from '@/types/crm';
import { formatMoney } from '@/lib/documents/generateDocumentText';
import type { CrmSettings } from '@/types/crm';
export function ClientDetails({ client, deals, settings, onEditClient, onDeleteClient, onCreateDeal }: { client: Client | null; deals: Deal[]; settings: CrmSettings; onEditClient: (client: Client) => void; onDeleteClient: (client: Client) => void; onCreateDeal: () => void }) {
  if (!client) return <div className="rounded-3xl border border-dashed border-slate-300 bg-white p-8 text-center text-sm text-slate-500">Клиент не выбран.</div>;
  return <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-slate-500">Карточка клиента</p><h2 className="mt-2 text-2xl font-bold text-slate-950">{client.name}</h2><p className="text-slate-500">{client.company}</p></div><div className="flex flex-wrap gap-2"><Button type="button" variant="outline" onClick={() => onEditClient(client)}><Pencil className="h-4 w-4" />Редактировать</Button><Button type="button" variant="outline" onClick={() => onDeleteClient(client)}><Trash2 className="h-4 w-4" />Удалить</Button><Button type="button" onClick={onCreateDeal}>Создать сделку</Button></div></div><div className="mt-5 grid gap-3 md:grid-cols-2"><p className="flex items-center gap-2 rounded-2xl bg-slate-50 p-3 text-sm"><Phone className="h-4 w-4" />{client.phone || 'Телефон не указан'}</p><p className="flex items-center gap-2 rounded-2xl bg-slate-50 p-3 text-sm"><Mail className="h-4 w-4" />{client.email || 'Email не указан'}</p><p className="flex items-center gap-2 rounded-2xl bg-slate-50 p-3 text-sm"><MessageCircle className="h-4 w-4" />{client.messengers.join(', ') || 'Мессенджеры не указаны'}</p><p className="flex items-center gap-2 rounded-2xl bg-slate-50 p-3 text-sm"><MapPin className="h-4 w-4" />{client.address || 'Адрес не указан'}</p></div><div className="mt-5 rounded-2xl bg-slate-50 p-4 text-sm text-slate-600"><p className="font-semibold text-slate-950">Комментарии</p><p className="mt-2">{client.comments || 'Комментариев пока нет.'}</p></div><div className="mt-5"><h3 className="font-bold text-slate-950">Сделки клиента</h3><div className="mt-3 grid gap-3 md:grid-cols-2">{deals.map((deal) => <article key={deal.id} className="rounded-2xl border border-slate-200 bg-slate-50 p-3"><p className="font-semibold text-slate-950">{deal.title}</p><p className="mt-1 text-sm text-slate-500">{deal.owner} · {deal.dueDate}</p><p className="mt-2 font-bold text-slate-950">{formatMoney(deal.revenueAmount, settings.money)}</p></article>)}</div></div></div>;
}
